/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROGRAMA_02;

/**
 *
 * @author DAW
 */
public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    public Tienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Contenedor = new javax.swing.JPanel();
        text_EnunciadoPrecio = new javax.swing.JTextField();
        text_EnunciadoUnidades = new javax.swing.JTextField();
        text_EnunciadoDescuento = new javax.swing.JTextField();
        text_EnunciadoIVA = new javax.swing.JTextField();
        text_PrecioArt = new javax.swing.JTextField();
        text_Unidades = new javax.swing.JTextField();
        text_Descuento = new javax.swing.JTextField();
        text_IVA = new javax.swing.JTextField();
        text_PrecioFinal = new javax.swing.JTextField();
        btn_Calcular = new javax.swing.JButton();
        label_PrecioFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_EnunciadoPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_EnunciadoPrecio.setText("Precio Artículo: ");

        text_EnunciadoUnidades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_EnunciadoUnidades.setText("Unidades: ");

        text_EnunciadoDescuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_EnunciadoDescuento.setText("Descuento: ");

        text_EnunciadoIVA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_EnunciadoIVA.setText("IVA: ");

        text_PrecioArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        text_Unidades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        text_Descuento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        text_IVA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        text_PrecioFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_PrecioFinal.setText("Precio Final: ");

        btn_Calcular.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_Calcular.setText("Calcular");
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        label_PrecioFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel_ContenedorLayout = new javax.swing.GroupLayout(panel_Contenedor);
        panel_Contenedor.setLayout(panel_ContenedorLayout);
        panel_ContenedorLayout.setHorizontalGroup(
            panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ContenedorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ContenedorLayout.createSequentialGroup()
                        .addGroup(panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_EnunciadoPrecio)
                            .addComponent(text_EnunciadoUnidades)
                            .addComponent(text_EnunciadoDescuento)
                            .addComponent(text_EnunciadoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ContenedorLayout.createSequentialGroup()
                                .addComponent(text_PrecioArt, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addGap(389, 389, 389))
                            .addGroup(panel_ContenedorLayout.createSequentialGroup()
                                .addGroup(panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(text_Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(text_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(text_IVA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(text_PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(label_PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panel_ContenedorLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        panel_ContenedorLayout.setVerticalGroup(
            panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ContenedorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ContenedorLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ContenedorLayout.createSequentialGroup()
                        .addGroup(panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ContenedorLayout.createSequentialGroup()
                                .addComponent(text_EnunciadoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(text_EnunciadoUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_ContenedorLayout.createSequentialGroup()
                                .addComponent(text_PrecioArt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(text_Unidades, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(text_Descuento, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(text_EnunciadoDescuento))
                        .addGap(29, 29, 29)
                        .addGroup(panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_EnunciadoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addComponent(btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        // TODO add your handling code here:
        double precioArticulo, precioFinal;
        int unidades, descuento, IVA;
        try{
            precioArticulo=Double.parseDouble(text_PrecioArt.getText());
            unidades=Integer.parseInt(text_Unidades.getText());
            descuento=Integer.parseInt(text_Descuento.getText());
            IVA=Integer.parseInt(text_IVA.getText());
            double precio_con_Descuento=(precioArticulo*unidades)-((precioArticulo*descuento)/100);
            precioFinal=precio_con_Descuento+((precio_con_Descuento*IVA)/100);
            label_PrecioFinal.setText(String.valueOf(precioFinal));
        }catch(NumberFormatException e){
            System.out.println(e.getMessage());
            e.printStackTrace();
        }catch(Exception e){
            System.out.println(e.getMessage());
            e.printStackTrace();
        }  
        
    }//GEN-LAST:event_btn_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JLabel label_PrecioFinal;
    private javax.swing.JPanel panel_Contenedor;
    private javax.swing.JTextField text_Descuento;
    private javax.swing.JTextField text_EnunciadoDescuento;
    private javax.swing.JTextField text_EnunciadoIVA;
    private javax.swing.JTextField text_EnunciadoPrecio;
    private javax.swing.JTextField text_EnunciadoUnidades;
    private javax.swing.JTextField text_IVA;
    private javax.swing.JTextField text_PrecioArt;
    private javax.swing.JTextField text_PrecioFinal;
    private javax.swing.JTextField text_Unidades;
    // End of variables declaration//GEN-END:variables
}
